# Generated by Django 4.2.2 on 2023-06-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('Flat', 'Flat'), ('1Room', '1Room'), ('2Room', '2Room')], max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
