# Generated by Django 4.2.2 on 2023-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
